server
{
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;

	# Ensure the server name matches your domain exactly
	server_name eala-lah.42.fr;

	# Subject requires strictly TLSv1.2 and/or TLSv1.3
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;

	root /var/www/html;
	index index.php index.html index.htm;

	location /
	{
		# Crucial for WordPress permalinks to work
		try_files $uri $uri/ /index.php?$args;
	}

	# WebSocket Proxy for GoAccess
	location /ws
	{
		proxy_pass http://goaccess:7890;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
		proxy_set_header Host $host;
	}

	location ~ \.php$
	{
		# Split path info to handle complex PHP requests
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		
		# Pass the request to the wordpress container on port 9000
		fastcgi_pass wordpress:9000;
		fastcgi_index index.php;
		
		include fastcgi_params;
		
		# Define the script filename for PHP-FPM
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}
}
