[www]
; Unix user/group of processes
; Aligned with Alpine's standard web user (nobody)
user	= nobody
group	= nobody

; Listen on port 9000 across all network interfaces to receive NGINX requests
listen	= 0.0.0.0:9000

; Set permissions for the listener
listen.owner	= nobody
listen.group	= nobody

; Process Manager Settings (Dynamic scaling for resource efficiency)
pm					= dynamic
pm.max_children		= 5
pm.start_servers	= 2
pm.min_spare_servers	= 1
pm.max_spare_servers	= 3

; Environment Variable Security
; Crucial: 'no' allows Docker .env secrets (like DB passwords) to reach WordPress
clear_env	= no
